parameters:
    media_class_path: "Dacorp\\ExtraBundle\\Entity\\"

jms_security_extra:
    secure_all_services: false
    expressions: true

knp_paginator:
    page_range: 5                      # default page range used in pagination control
    default_options:
        distinct: true                 # ensure distinct results, useful when ORM queries are using GROUP BY statements
    template:
        pagination: KnpPaginatorBundle:Pagination:sliding.html.twig     # sliding pagination controls template
        sortable: KnpPaginatorBundle:Pagination:sortable_link.html.twig # sort link template

fos_user:
    db_driver: orm
    firewall_name: main
    # user class should be defined in the main app config file
    user_class: Dacorp\ExtraBundle\Entity\User
    service:
        user_manager: pugx_user_manager
      
assetic:
    filters:
        less:
            node: /usr/bin/node
            node_paths: [/usr/lib/node_modules]
            apply_to: "\.less$"


# default configuration for contact bundle
mremi_contact:
    store_data:            false
    contact_class:         Dacorp\ExtraBundle\Entity\Contact

    form:
        type:              mremi_contact
        name:              contact_form
        validation_groups: [Default]
        subject_provider:  mremi_contact.subject_provider.noop
        captcha_disabled:  false
        captcha_type:      genemu_captcha

    email:
        mailer:            mremi_contact.mailer.twig_swift
        recipient_address: webmaster@popolipopo.com
        template:          MremiContactBundle:Contact:email.txt.twig


#jms_i18n_routing:
#    default_locale: en
#    locales: [en, de, fr]
#    strategy: prefix