register_openid:
    path:  /register-openid
    defaults: { _controller: DacorpExtraBundle:User:registerOpenId }

edit_own_profile:
    path:  /profile/edit
    defaults: { _controller: DacorpExtraBundle:User:editOwnProfile }

show_own_profile:
    path:  /my-profile
    defaults: { _controller: DacorpExtraBundle:User:showOwnProfile }

show_profile:
    path:  /show/{username}
    defaults: { _controller: DacorpExtraBundle:User:showProfile }